/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarian;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AddBooks extends javax.swing.JFrame {

    /**
     * Creates new form AddBooks
     */
    public AddBooks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textcallNo = new javax.swing.JTextField();
        textName = new javax.swing.JTextField();
        textAuth = new javax.swing.JTextField();
        textPublisher = new javax.swing.JTextField();
        textQuantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        textIssued = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Add Books");

        jLabel2.setText("Call No. :");

        jLabel3.setText("Name:");

        jLabel4.setText("Author:");

        jLabel5.setText("Publisher:");

        jLabel6.setText("Quantity: ");

        textcallNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcallNoActionPerformed(evt);
            }
        });

        jButton1.setText("Add Books");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("how many issued?");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textcallNo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textPublisher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(textAuth, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textQuantity)
                    .addComponent(textIssued))
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textcallNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textAuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textIssued, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public static void saveFile() throws FileNotFoundException, IOException
{    
    
     File f= new File("books.txt");
    PrintWriter p=new PrintWriter(f); 
    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
    for(int i=0;i<BooksCommonTasks.count;i++)
    {
       p.println(BooksCommonTasks.u[i].getCallNo()+","+BooksCommonTasks.u[i].getName()
               +","+BooksCommonTasks.u[i].getAuthor()+","+BooksCommonTasks.u[i].getPublisher()+","+BooksCommonTasks.u[i].getQuantity()
               +","+BooksCommonTasks.u[i].getIssued()+","+BooksCommonTasks.u[i].getDate()); 
    }

    p.close();
}
    private void textcallNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcallNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcallNoActionPerformed

    boolean checkValid (String quantity, String issued, String callNo){
        int i;
        for (i=0; i<quantity.length(); i++)
            {
                if ( quantity.charAt(i)>'9' || quantity.charAt(i)< '0' )
                {
                    JOptionPane.showMessageDialog(null, "Incorrect Quantity.");
                    return false;
                }
            }
            for (i=0; i<issued.length(); i++)
            {
                if ( issued.charAt(i)>'9' || issued.charAt(i)< '0' )
                {
                    JOptionPane.showMessageDialog(null, "Incorrect issued .");
                   return false;

                }
            }
            if (callNo.charAt(0)>='A' && callNo.charAt(0)<='Z'&& callNo.charAt(1)>='@' && callNo.charAt(2)>='0' && callNo.charAt(2)<='9' ) return true;
            else
            {
               JOptionPane.showMessageDialog(null, "Incorrect CallNo.");
                return false;
            }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String callNo = textcallNo.getText();
         String name = textName.getText();
         String auth = textAuth.getText();
         String publisher = textPublisher.getText();
         String quantity = textQuantity.getText();
         String issued =textIssued.getText();
         boolean valid;
         Date currentDate;
        try {
            
            BooksCommonTasks.readFiles();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AddBooks.class.getName()).log(Level.SEVERE, null, ex);
        }
        int i; boolean check = true; 
        if (name.equals("") || callNo.equals("") || auth.equals("") || publisher.equals("") || quantity.equals("") || issued.equals(""))
               JOptionPane.showMessageDialog (null, "You must fill all the data.");
        else{
          valid = checkValid(quantity,issued,callNo); 
            if (valid)
            {
             for (i=0; i<BooksCommonTasks.count; i++)
        {
            if ( BooksCommonTasks.u[i].getAuthor().equals(auth)
                  &&  BooksCommonTasks.u[i].getCallNo().equals(callNo) 
                   && BooksCommonTasks.u[i].getName().equals(name) && BooksCommonTasks.u[i].getPublisher().equals(publisher))
            {
                    check = false;
                    int quantitnInt = Integer.parseInt(quantity);
                    int existQuantity = Integer.parseInt(BooksCommonTasks.u[i].getQuantity());
                    int z = quantitnInt + existQuantity;
                    String ret = Integer.toString(z);
                    BooksCommonTasks.u[i].setQuantity(ret);
                    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                    currentDate =new Date(System.currentTimeMillis());
                    String d ;
                    SimpleDateFormat sdff=new SimpleDateFormat("yyyy-MM-dd");
            try {
                d = sdff.format(currentDate);
                 BooksCommonTasks.u[i].setDate(d);
                    JOptionPane.showMessageDialog(null, "there is the same book callno,we added the Quantity");
                    saveFile();
                    LibrarianSection x = new LibrarianSection();
                    this.hide();
                    x.setVisible(true);
                    break;
                } catch (IOException ex) {
                    Logger.getLogger(AddBooks.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
            else if (BooksCommonTasks.u[i].getCallNo().equals(callNo)) 
            {
                JOptionPane.showMessageDialog(null, "This Book is arleady used");
                check = false;
            }
        }
            if (check==true){
             try {
                 BooksCommonTasks.u[BooksCommonTasks.count] = new UserBooks(callNo,name,auth,publisher,quantity,issued);
                 BooksCommonTasks.count++;
                 JOptionPane.showMessageDialog(null, "Book added successfully!");
                 LibrarianSection x = new LibrarianSection();
                 this.hide();
                 x.setVisible(true);
                 BooksCommonTasks.writeFile();
             } catch (IOException ex) {
                 Logger.getLogger(AddBooks.class.getName()).log(Level.SEVERE, null, ex);
             }}}}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         LibrarianSection x = new LibrarianSection();
         this.hide();
         x.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

         
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textAuth;
    private javax.swing.JTextField textIssued;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textPublisher;
    private javax.swing.JTextField textQuantity;
    private javax.swing.JTextField textcallNo;
    // End of variables declaration//GEN-END:variables
}
