/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarian;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static librarian.IssuedCommonTasks.count;
import static librarian.IssuedCommonTasks.u;
import student.StudentsCommonTasks;

/**
 *
 * @author HP
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textcallNo = new javax.swing.JTextField();
        textStudentId = new javax.swing.JTextField();
        issueBooks = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        textName = new javax.swing.JTextField();
        textContact = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textReturned = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Call No. :");

        jLabel3.setText("Student id:");

        jLabel4.setText("student name:");

        jLabel5.setText("student contact:");

        textcallNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcallNoActionPerformed(evt);
            }
        });

        issueBooks.setText("Issue Book");
        issueBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBooksActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Issue Books");

        jLabel6.setBackground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("note:please check student ID carefully befor issuing book!");

        jLabel8.setText("Enter return date:");

        jLabel7.setText("(YYYY-MM-DD)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(issueBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                    .addComponent(textReturned, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(82, 82, 82)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(textContact, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                        .addComponent(textName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textStudentId, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textcallNo, javax.swing.GroupLayout.Alignment.LEADING)))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textcallNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textReturned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(13, 13, 13)
                .addComponent(issueBooks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void saveFile() throws FileNotFoundException, IOException
{    
    
     File f= new File("books.txt");
    PrintWriter p=new PrintWriter(f); 
    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
    for(int i=0;i<BooksCommonTasks.count;i++)
    {
       p.println(BooksCommonTasks.u[i].getCallNo()+","+BooksCommonTasks.u[i].getName()
               +","+BooksCommonTasks.u[i].getAuthor()+","+BooksCommonTasks.u[i].getPublisher()+","+BooksCommonTasks.u[i].getQuantity()
               +","+BooksCommonTasks.u[i].getIssued()+","+BooksCommonTasks.u[i].getDate()); 
    }

    p.close();
}
    public boolean checkValid(String callNo, String id, String contactNo, String date)
    {  
        int i;
         for (i=0; i<id.length(); i++)
         {
     if (id.charAt(i)>'9' || id.charAt(i)<'0' )
                {
                 JOptionPane.showMessageDialog(null, "Incorrect ID");
                  return  false;
                }}
    
    for (i=0; i< contactNo.length(); i++)
        {                  
                 if (contactNo.charAt(i) > '9' || contactNo.charAt(i) < '0')
                    {              
                    JOptionPane.showMessageDialog(null, "Incorrect contact number");
                    return false;
                    }
        }
     String tokens[]= date.split("-");
     if (Integer.parseInt(tokens[0])<2021 || Integer.parseInt(tokens[1])>12 || 
             Integer.parseInt(tokens[1])<1 || Integer.parseInt(tokens[2])<1 || Integer.parseInt(tokens[2])>31 )
     {
         JOptionPane.showMessageDialog(null, "Incorrect Date");
         return false;
     }
    if (callNo.charAt(0)>='A' && callNo.charAt(0)<='Z'&& callNo.charAt(1)>='@' && callNo.charAt(2)>='0' && callNo.charAt(2)<='9' ) return true;
            else
            {
               JOptionPane.showMessageDialog(null, "Incorrect CallNo.");
                return false;
            }
    }
    private void textcallNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcallNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcallNoActionPerformed

    private void issueBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBooksActionPerformed
        // TODO add your handling code here:
         String bookCallNo = textcallNo.getText();
         String studentId = textStudentId.getText();
         String studentName = textName.getText();
         String studentContact = textContact.getText();
         String returnedDate=textReturned.getText();
        try {
            IssuedCommonTasks.readFiles();
            StudentsCommonTasks.readFiles();
            BooksCommonTasks.readFiles();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(IssueBook.class.getName()).log(Level.SEVERE, null, ex);
        }
         int i; boolean check = false; 
         boolean found=false; int x = 0; int j; int n=0;
         if (checkValid(bookCallNo,studentId,studentContact,returnedDate))
         {
        for (i=0;i<(StudentsCommonTasks.count);i++)
        {
            if (StudentsCommonTasks.u[i].getId().equals(studentId) && StudentsCommonTasks.u[i].getUserName().equals(studentName))
            {
                found=true;            
                 for( j=0; j<IssuedCommonTasks.count; j++)
                     {  
                         if(IssuedCommonTasks.u[j].getStudentId().equals(studentId))
                                 {
                                         x++;
                                 }
                      }
                 break;
            }
        }
        for (i=0; i<BooksCommonTasks.count ; i++)
        {
            if (BooksCommonTasks.u[i].getCallNo().equals(bookCallNo))
            {
                n = i;
                check = true;
                break;
            }
        }
        if (Integer.parseInt(BooksCommonTasks.u[n].getQuantity() )== 0 ) JOptionPane.showMessageDialog(null, "The book is out of stock!!");
        else if( x >= 3) JOptionPane.showMessageDialog(null, "You issued the maximum number of books!!");
        else if (!check) JOptionPane.showMessageDialog(null, "The book is not existing!!");
        else if (!found) JOptionPane.showMessageDialog(null, "Wrong ID or NAME!!");
        else{
                    int quantityInt = Integer.parseInt(BooksCommonTasks.u[n].getQuantity());
                    int issuedInt = Integer.parseInt(BooksCommonTasks.u[n].getIssued());
                    quantityInt--;
                    issuedInt++;
                    String quantityRet = Integer.toString(quantityInt);
                    String issuedRet =  Integer.toString(issuedInt);
                    BooksCommonTasks.u[n].setQuantity(quantityRet);
                    BooksCommonTasks.u[n].setIssued(issuedRet);
                    IssuedCommonTasks.u[IssuedCommonTasks.count] = new IssuedUser(bookCallNo,studentId,studentName,studentContact,returnedDate);
                    IssuedCommonTasks.count++;
                     JOptionPane.showMessageDialog(null, "Book issued successfully!");
            try {
                 saveFile();
             } catch (IOException ex) {
                 Logger.getLogger(IssueBook.class.getName()).log(Level.SEVERE, null, ex);
             }
             try {
                 IssuedCommonTasks.writeFile();
             } catch (IOException ex) {
                 Logger.getLogger(IssueBook.class.getName()).log(Level.SEVERE, null, ex);
             }
             
         }
       
        LibrarianSection m = new LibrarianSection();
        this.hide();
        m.setVisible(true);}
        
    }//GEN-LAST:event_issueBooksActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LibrarianSection x = new LibrarianSection();
        this.hide();
        x.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton issueBooks;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textContact;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textReturned;
    private javax.swing.JTextField textStudentId;
    private javax.swing.JTextField textcallNo;
    // End of variables declaration//GEN-END:variables
}
