/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarian;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() throws FileNotFoundException {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bookCallNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        studentId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Return Book");

        jLabel2.setText("Book Callno.: ");

        bookCallNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookCallNoActionPerformed(evt);
            }
        });

        jLabel3.setText("Student ID:");

        jButton1.setText("Return Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Note: check the book property!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studentId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookCallNo))
                        .addGap(82, 82, 82))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton1)))
                .addGap(42, 178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bookCallNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(studentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void deleteFile() throws FileNotFoundException, IOException  
{
    String id = studentId.getText(); 
    int i,j=0;
    IssuedCommonTasks.readFiles();
        for (i=0; i< IssuedCommonTasks.count; i++)
        {
            if ( IssuedCommonTasks.u[i].getStudentId().equals(id)) { 
                for (j=i; j< IssuedCommonTasks.count-1; j++)
                {
                  IssuedCommonTasks.u[j] =  IssuedCommonTasks.u[j+1]; 
                }
            IssuedCommonTasks.count--;
             break;
        }       
    }                
}
 public static void saveFile() throws FileNotFoundException, IOException
{    
    
     File f= new File("books.txt");
    PrintWriter p=new PrintWriter(f);
    File k = new File("IssuedBooks.txt"); 
    SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
    PrintWriter c =new PrintWriter(k); 
    int i;
    for( i=0;i<BooksCommonTasks.count;i++)
    {
       p.println(BooksCommonTasks.u[i].getCallNo()+","+BooksCommonTasks.u[i].getName()
               +","+BooksCommonTasks.u[i].getAuthor()+","+BooksCommonTasks.u[i].getPublisher()+","+BooksCommonTasks.u[i].getQuantity()
               +","+BooksCommonTasks.u[i].getIssued()+","+BooksCommonTasks.u[i].getDate()); 
    } 
    for( i=0; i<IssuedCommonTasks.count;i++)
    {
       c.println(IssuedCommonTasks.u[i].getCallNo()+","+IssuedCommonTasks.u[i].getStudentId()
               +","+IssuedCommonTasks.u[i].getStudentName()+","+IssuedCommonTasks.u[i].getStudentContact()+","
               +IssuedCommonTasks.u[i].getIssuedDate()+","+IssuedCommonTasks.u[i].getReturnedDate()); 
    }
    c.close();
    p.close(); 

}
boolean checkValid (String id, String callNo)
{
    int i;
    boolean valid = true;
    for (i=0; i<id.length(); i++)
         {
     if (id.charAt(i)>'9' || id.charAt(i)<'0' )
                {
                 JOptionPane.showMessageDialog(null, "Incorrect ID");
                  valid =false;
                }}
     if (callNo.charAt(0)>='A' && callNo.charAt(0)<='Z'&& callNo.charAt(1)>='@' && callNo.charAt(2)>='0' && callNo.charAt(2)<='9' ) return true;
            else
            {
               JOptionPane.showMessageDialog(null, "Incorrect CallNo.");
                return false;
            }
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String callNo = bookCallNo.getText();
        String id = studentId.getText();
        String retDate = "";
        Date currentDate;
         Boolean found=false;
         Boolean check=false;
         int n=0;
        try {
            IssuedCommonTasks.readFiles();
            BooksCommonTasks.readFiles();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        }
      if (checkValid(id,callNo))
      {
         
         for (int i=0;i<(IssuedCommonTasks.count);i++)
        {
            if (IssuedCommonTasks.u[i].getCallNo().equals(callNo) && IssuedCommonTasks.u[i].getStudentId().equals(id))
            {
                check=true;
                retDate = IssuedCommonTasks.u[i].getReturnedDate();
                for (int j=0; j<BooksCommonTasks.count; j++)
                {
                    if (BooksCommonTasks.u[j].getCallNo().equals(callNo))
                        n = j;
                }
                 break;
            }           
        }
         if (!check ){ JOptionPane.showMessageDialog(null,"Sorry unable to return Book!!");
         JOptionPane.showMessageDialog(null,"Please check your ID or book callno!!");}
         
        else 
        {
                    int quantityInt = Integer.parseInt(BooksCommonTasks.u[n].getQuantity());
                    int issuedInt = Integer.parseInt(BooksCommonTasks.u[n].getIssued());
                    quantityInt++;
                    issuedInt--;
                    String quantityRet = Integer.toString(quantityInt);
                    String issuedRet =  Integer.toString(issuedInt);
                    BooksCommonTasks.u[n].setQuantity(quantityRet);
                    BooksCommonTasks.u[n].setIssued(issuedRet);
                    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                    currentDate=new Date(System.currentTimeMillis());
                    Date d = null;
            try {
                d = sdf.parse(retDate);
                  if ((sdf.format(currentDate).compareTo(sdf.format(d))) <=0) JOptionPane.showMessageDialog(null,"Book returned successfully and NO penalety!");
                  else JOptionPane.showMessageDialog(null,"Book returned successfully and you have 50 L.E penalety!");
                deleteFile();
                saveFile();
                
            }
             catch (IOException ex) {
                Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                 LibrarianSection x=new LibrarianSection();
                 x.setVisible(true);
                 this.hide();   }           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LibrarianSection x = new LibrarianSection();
            this.hide();
            x.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bookCallNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookCallNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookCallNoActionPerformed

    /**
     * @param args the command line arguments
     */
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookCallNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField studentId;
    // End of variables declaration//GEN-END:variables
}
